[package]
name = "7kayoh/koute"
author = ["7kayoh<git@7kayoh.net>"]
license = "MIT"
version = "0.1.0-beta"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.1.1-beta"