[package]
name = "7kayoh/koute"
description = "Koute. Routing in Fusion supercharged."
license = "MIT"
author = ["7kayoh<shigoto@7kayoh.net>"]
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.1.1-beta"